spring:
  application:
    name: patient-observation
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.cloud.consul.discovery.service-name}-${random.uuid}
    stream:
      bindings:
        sendHeartRates-out-0:
          destination: heartRate-topic
        receiveHeartRates-in-0:
          destination: heartRate-topic
    function:
      definition: sendHeartRates; receiveHeartRates
  graphql:
    path: /graphql
    websocket:
      path: /graphql
    graphiql:
      enabled: true
  sql:
    init:
      mode: always