spring:
  cloud:
    stream:
      bindings:
        sendSpO2-out-0:
          destination: spO2-topic
        receiveSpO2-in-0:
          destination: spO2-topic
    function:
      definition: sendSpO2; receiveSpO2
  graphql:
    path: /graphql
    websocket:
      path: /graphql
    graphiql:
      enabled: true
  sql:
    init:
      mode: always